# Generated by Django 2.0 on 2020-05-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='users',
            new_name='owner',
        ),
    ]
