# Generated by Django 3.0.6 on 2020-05-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0017_auto_20200530_1239'),
        ('app', '0002_comments_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
