# Generated by Django 3.0.6 on 2020-06-03 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20200603_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='ownerID',
        ),
        migrations.AddField(
            model_name='comments',
            name='owner',
            field=models.ForeignKey(default='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
